import { Component } from '@angular/core';

@Component({
  selector: 'app-badges',
  templateUrl: './badges.component.html',
  styleUrls: ['./badges.component.css']
})
export class BadgesComponent {
  badgeArray  = [
    
    { name:"Angular" , 
      source:"https://angular.io/assets/images/logos/angular/angular.svg", 
      link:"https://angular.io" },
    { name:"Vue3" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/vuejs/vuejs-original-wordmark.svg", 
      link:"https://vuejs.org/" },
    { name:"React" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg", 
      link:"https://reactjs.org/" },
    { name:"Html5" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg", 
      link:"https://www.w3.org/html/" },
    { name:"Css3"  , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg", 
      link:"https://www.w3schools.com/css/" },
    { name:"Saas"  , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg", 
      link:"https://sass-lang.com" },
    { name:"Bootstrap" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-plain-wordmark.svg", 
      link:"https://getbootstrap.com" },
    { name:"Material" , 
      source:"https://material.angular.io/assets/img/angular-material-logo.svg", 
      link:"https://material.angular.io/" },
    { name:"Javascript" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg", 
      link:"https://developer.mozilla.org/en-US/docs/Web/JavaScript" },
    { name:"Typescript" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg", 
      link:"https://www.typescriptlang.org/" },
    { name:"Next" , 
      source:"https://cdn.worldvectorlogo.com/logos/nextjs-2.svg", 
      link:"https://nextjs.org/" },
    { name:"Lit" , 
      source:"https://lit.dev/images/logo.svg", 
      link:"https://lit.dev/" },
    { name:"Gatsby" , 
      source:"https://www.vectorlogo.zone/logos/gatsbyjs/gatsbyjs-icon.svg", 
      link:"https://www.gatsbyjs.com/" },
    { name:"Nodejs" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg", 
      link:"https://nodejs.org" },
    { name:"Express" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg", 
      link:"https://expressjs.com" },
    { name: "Sonar",
      source:"https://assets-eu-01.kc-usercontent.com/c196a450-1482-01db-440a-964b8358d017/889c710e-6b94-4802-b299-a2e169107e42/SonarCloud_Logo.svg",
      link:"https://www.sonarsource.com/products/sonarcloud/",
    },
    { name:"Nest" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/nestjs/nestjs-plain.svg", 
      link:"https://nestjs.com/" },
    { name:"Jest" , 
      source:"https://www.vectorlogo.zone/logos/jestjsio/jestjsio-icon.svg", 
      link:"https://jestjs.io" },
    { name:"Jasmine" , 
      source:"https://www.vectorlogo.zone/logos/jasmine/jasmine-icon.svg", 
      link:"https://jasmine.github.io/" },
    { name:"Cypress" , 
      source:"https://raw.githubusercontent.com/simple-icons/simple-icons/6e46ec1fc23b60c8fd0d2f2ff46db82e16dbd75f/icons/cypress.svg", 
      link:"https://www.cypress.io" },
    { name:"Python" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg", 
      link:"https://www.python.org" },
    { name:"Flask" , 
      source:"https://www.vectorlogo.zone/logos/pocoo_flask/pocoo_flask-icon.svg", 
      link:"https://flask.palletsprojects.com/" },
    { name:"Mongo" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg", 
      link:"https://www.mongodb.com/" },
    { name:"Postgresql" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original-wordmark.svg", 
      link:"https://www.postgresql.org" },
    { name:"Docker" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/docker/docker-original-wordmark.svg", 
      link:"https://www.docker.com/" },
    { name:"Firebase" , 
      source:"https://www.vectorlogo.zone/logos/firebase/firebase-icon.svg", 
      link:"https://firebase.google.com/" },
    { name:"Git" , 
      source:"https://www.vectorlogo.zone/logos/git-scm/git-scm-icon.svg", 
      link:"https://git-scm.com/" },
    { name:"Linux" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/linux/linux-original.svg", 
      link:"https://www.linux.org/" },
    { name:"C-Lang" , 
      source:"https://raw.githubusercontent.com/devicons/devicon/master/icons/c/c-original.svg", 
      link:"https://www.cprogramming.com/" },
    { name:"Bash" , 
      source:"https://www.vectorlogo.zone/logos/gnu_bash/gnu_bash-icon.svg", 
      link:"https://www.gnu.org/software/bash/" },
  ]
}
